server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true

knife4j:
  enable: true
  setting:
    language: zh_cn
spring:
  application:
    name: cloudmart-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        import-check:
          enabled: false
    gateway:
      routes:
        #=======Auth服务========
        - id: auth-service
          uri: lb://cloudmart-auth
          predicates:
            - Path=/api/auth/**


        #=======Product服务========
        - id: product-service
          uri: lb://cloudmart-product
          predicates:
            - Path=/api/products/**,/api/categories/**,/api/favorites/**,/api/admin/products/**,/api/admin/categories/**



        #=======Order服务========
        - id: order-service
          uri: lb://cloudmart-order
          predicates:
            - Path=/api/cart/**,/api/orders/**,/api/coupons/**,/api/seckill/**,/api/admin/orders/**,/api/admin/coupons/**,/api/admin/seckill/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"

        #全局过滤器，去掉重复的跨域头
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin

